name: Country Time Fetcher

on:
  workflow_dispatch:

jobs:

  prepare-matrix:
    runs-on: ubuntu-latest

    outputs:
      countries: ${{ steps.matrix.outputs.countries }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Dynamic Matrix
        id: matrix
        run: |
          countries=$(jq -R -s -c 'split("\n")[:-1]' source.txt)

          echo "countries=$countries" >> "$GITHUB_OUTPUT"

          echo "Generated Matrix:"
          echo "$countries"

  fetch-time:
    needs: prepare-matrix

    runs-on: ubuntu-latest

    strategy:
      matrix:
        country: ${{ fromJson(needs.prepare-matrix.outputs.countries) }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install countryinfo pytz

      - name: Fetch Time For Country
        run: |
          python get_time.py "${{ matrix.country }}"

      - name: Upload Country Result
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.country }}
          path: ${{ matrix.country }}.txt

  combine-results:
    needs: fetch-time

    runs-on: ubuntu-latest

    steps:
      - name: Download All Results
        uses: actions/download-artifact@v4
        with:
          path: results

      - name: Create output.txt
        run: |
          find results -name "*.txt" -exec cat {} \; > output.txt

          echo "Final Output:"
          cat output.txt

      - name: Upload Final Output
        uses: actions/upload-artifact@v4
        with:
          name: final-output
          path: output.txt
